export const FORECAST_SET_FETCH_STATUS = "FORECAST_SET_FETCH_STATUS";
export const FORECAST_RECEIVE_FORECAST = "FORECAST_RECEIVE_FORECAST";
export const CITIES_SET_FETCH_STATUS = "CITIES_SET_FETCH_STATUS";
export const CITIES_RECEIVE_CITIES = "CITIES_RECEIVE_CITIES";
