export const FORECAST_SET_FETCH_STATUS = "FORECAST_SET_FETCH_STATUS";
export const FORECAST_REQUEST_FORECAST = "FORECAST_REQUEST_FORECAST";
export const FORECAST_RECEIVE_FORECAST = "FORECAST_RECEIVE_FORECAST";

export const CITIES_SET_FETCH_STATUS = "CITIES_SET_FETCH_STATUS";
export const CITIES_REQUEST_CITIES = "CITIES_REQUEST_CITIES";
export const CITIES_RECEIVE_CITIES = "CITIES_RECEIVE_CITIES";
